import { PrismaClient } from '@prisma/client';

export const SEED_ROLES: Array<{
  name: string;
  description: string;
  isSystem: boolean;
  permissions: string[];
}> = [
  {
    name: 'admin',
    description: 'Platform super administrator',
    isSystem: true,
    permissions: [
      'manage:all',
      'manage:announcements',
      'create:announcements',
      'read:announcements',
      'update:announcements',
      'delete:announcements',
      'manage:broadcast',
      'create:broadcast',
      'read:broadcast',
      'manage:notification-templates',
      'create:notification-templates',
      'read:notification-templates',
      'update:notification-templates',
      'delete:notification-templates',
      'read:analytics',
      'create:custom-reports',
      'read:search',
      'manage:billing-plans',
      'manage:coupons',
      'manage:refunds',
      'manage:feature-flags',
      'read:feature-flags',
      'update:feature-flags',
      'delete:feature-flags',
      'manage:system-settings',
      'read:system-settings',
      'manage:backups',
      'read:backups',
      'read:audit-logs',
      'read:api-usage',
      'read:error-monitoring',
      'read:health',
    ],
  },
  {
    name: 'student',
    description: 'College student on the platform',
    isSystem: true,
    permissions: [
      'read:self',
      'read:sessions',
      'delete:sessions',
      'manage:student-profile',
      'manage:skills',
      'manage:career-goals',
      'manage:calendar',
      'manage:settings',
      'manage:notifications',
      'manage:readiness',
      'read:activity',
      'read:dashboard',
      'read:academics-departments',
      'read:academics-semesters',
      'read:academics-subjects',
      'read:academics-materials',
      'read:academics-timetable',
      'read:academics-exams',
      'read:academics-assignments',
      'create:academics-assignments',
      'read:academics-attendance',
      'read:academics-marks',
      'read:academics-gpa',
      'read:academics-cgpa',
      'read:academics-calendar',
      'read:placement-roadmap',
      'read:placement-company-prep',
      'read:placement-progress',
      'read:placement-readiness',
      'read:placement-daily-challenge',
      'create:placement-study-planner',
      'update:placement-tasks',
      'read:dsa-problems',
      'create:dsa-problems',
      'read:dsa-submissions',
      'create:dsa-submissions',
      'read:dsa-editorial',
      'read:dsa-hints',
      'create:dsa-hints',
      'read:dsa-playlists',
      'create:dsa-playlists',
      'update:dsa-playlists',
      'delete:dsa-playlists',
      'read:dsa-sheets',
      'read:dsa-progress',
      'read:dsa-analytics',
      'read:dsa-profile',
      'update:dsa-profile',
      'read:dsa-discussion',
      'create:dsa-discussion',
      'read:dsa-contests',
      'create:dsa-registrations',
      'read:dsa-leaderboard',
      'read:dsa-rating',
      'create:dsa-anti-cheat',
      'create:interviews',
      'read:interviews',
      'read:interview-reports',
      'read:career-coach-roadmap',
      'read:career-coach-recommendations',
      'read:career-coach-salary',
      'read:career-coach-skill-gap',
      'create:career-coach-chat',
      'read:career-coach-chat',
      'create:resumes',
      'read:resumes',
      'update:resumes',
      'delete:resumes',
      'read:resume-templates',
      'create:resume-ats',
      'read:resume-ats',
      'read:resume-versions',
      'create:resume-versions',
      'create:battle-queue',
      'delete:battle-queue',
      'create:battles',
      'read:battles',
      'create:battle-submissions',
      'read:battle-ratings',
      'read:battle-history',
      'read:leaderboards',
      'read:gamification',
      'create:gamification',
      'claim:daily-reward',
      'read:certificates',
      'create:certificates',
      'read:jobs',
      'create:jobs',
      'update:jobs',
      'delete:jobs',
      'read:internships',
      'create:internships',
      'update:internships',
      'delete:internships',
      'read:mentors',
      'create:mentors',
      'update:mentors',
      'read:bookings',
      'create:bookings',
      'read:company-prep',
      'read:announcements',
      'read:search',
      'read:billing-plans',
      'create:subscriptions',
      'read:subscriptions',
      'cancel:subscriptions',
      'read:billing-invoices',
      'create:coupons',
      'request:refunds',
      'create:ai-tutor',
      'create:ai-doubt-solver',
      'create:ai-code-review',
      'create:ai-resume-analyzer',
      'create:ai-interview-evaluator',
      'create:ai-question-generator',
      'create:ai-study-planner',
      'create:forum-posts',
      'read:forum-posts',
      'update:forum-posts',
      'delete:forum-posts',
      'create:forum-comments',
      'read:forum-comments',
      'update:forum-comments',
      'delete:forum-comments',
      'create:forum-likes',
      'delete:forum-likes',
      'create:study-groups',
      'read:study-groups',
      'update:study-groups',
      'delete:study-groups',
      'create:study-group-members',
      'delete:study-group-members',
      'create:coding-clubs',
      'read:coding-clubs',
      'update:coding-clubs',
      'delete:coding-clubs',
      'create:coding-club-members',
      'delete:coding-club-members',
      'read:lab-subjects',
      'read:lab-experiments',
      'create:lab-submissions',
      'read:lab-submissions',
      'read:lab-assignments',
      'read:lab-exams',
      'create:lab-exams',
      'read:lab-vivas',
      'create:lab-projects',
      'update:lab-projects',
      'create:lab-attendance',
      'read:lab-attendance',
      'read:lab-analytics',
    ],
  },
  {
    name: 'faculty',
    description: 'College faculty member',
    isSystem: true,
    permissions: [
      'read:self',
      'read:faculty',
      'create:faculty',
      'manage:faculty-subjects',
      'manage:faculty-materials',
      'manage:faculty-attendance',
      'manage:faculty-assignments',
      'manage:faculty-exams',
      'manage:faculty-marks',
      'manage:faculty-question-bank',
      'read:faculty-analytics',
      'read:dsa-contests',
      'create:dsa-contests',
      'update:dsa-contests',
      'delete:dsa-contests',
      'read:dsa-leaderboard',
      'read:dsa-rating',
      'read:leaderboards',
      'read:certificates',
      'create:certificates',
      'read:mentors',
      'create:mentors',
      'update:mentors',
      'manage:bookings',
      'read:faculty-reports',
      'manage:faculty-broadcast',
      'create:announcements',
      'read:announcements',
      'create:broadcast',
      'read:broadcast',
      'read:analytics',
      'read:search',
      'read:lab-subjects',
      'create:lab-subjects',
      'update:lab-subjects',
      'delete:lab-subjects',
      'read:lab-experiments',
      'create:lab-experiments',
      'update:lab-experiments',
      'delete:lab-experiments',
      'read:lab-submissions',
      'update:lab-submissions',
      'create:lab-submissions',
      'read:lab-assignments',
      'create:lab-assignments',
      'update:lab-assignments',
      'delete:lab-assignments',
      'read:lab-exams',
      'create:lab-exams',
      'update:lab-exams',
      'delete:lab-exams',
      'read:lab-vivas',
      'create:lab-vivas',
      'update:lab-vivas',
      'delete:lab-vivas',
      'read:lab-projects',
      'update:lab-projects',
      'read:lab-attendance',
      'create:lab-obe',
      'read:lab-obe',
      'read:lab-analytics',
      'read:lab-reports',
    ],
  },
  {
    name: 'college_admin',
    description: 'College administrator',
    isSystem: true,
    permissions: [
      'read:self',
      'manage:departments',
      'manage:courses',
      'manage:faculty',
      'manage:students',
      'manage:academic-calendar',
      'read:academic-reports',
      'read:dsa-contests',
      'create:dsa-contests',
      'update:dsa-contests',
      'delete:dsa-contests',
      'read:dsa-leaderboard',
      'read:dsa-rating',
      'read:leaderboards',
      'manage:company-prep',
      'manage:announcements',
      'create:announcements',
      'read:announcements',
      'update:announcements',
      'delete:announcements',
      'manage:broadcast',
      'create:broadcast',
      'read:broadcast',
      'manage:notification-templates',
      'read:notification-templates',
      'read:analytics',
      'create:custom-reports',
      'read:search',
      'create:lab-subjects',
      'update:lab-subjects',
      'delete:lab-subjects',
      'create:lab-experiments',
      'update:lab-experiments',
      'delete:lab-experiments',
      'update:lab-submissions',
      'create:lab-assignments',
      'update:lab-assignments',
      'delete:lab-assignments',
      'create:lab-exams',
      'update:lab-exams',
      'delete:lab-exams',
      'create:lab-vivas',
      'update:lab-vivas',
      'delete:lab-vivas',
      'update:lab-projects',
      'read:lab-attendance',
      'create:lab-obe',
      'read:lab-obe',
      'read:lab-analytics',
      'read:lab-reports',
    ],
  },
  {
    name: 'recruiter',
    description: 'Company recruiter',
    isSystem: true,
    permissions: [
      'read:self',
      'read:jobs',
      'create:jobs',
      'update:jobs',
      'delete:jobs',
      'read:internships',
      'create:internships',
      'update:internships',
      'delete:internships',
      'manage:recruiter',
      'read:candidates',
      'manage:shortlist',
      'manage:interviews',
      'read:recruiter-analytics',
      'read:analytics',
      'read:search',
    ],
  },
  {
    name: 'tpo',
    description: 'Training & placement officer',
    isSystem: true,
    permissions: [
      'read:self',
      'manage:tpo',
      'manage:company-drives',
      'read:tpo-analytics',
      'manage:offers',
      'manage:tpo-interviews',
      'read:placement-reports',
      'read:department-stats',
      'manage:recruiter-coordination',
      'read:analytics',
      'create:custom-reports',
      'read:search',
    ],
  },
  {
    name: 'parent',
    description: 'Parent of a student',
    isSystem: true,
    permissions: ['read:self'],
  },
  {
    name: 'mentor',
    description: 'Mentor offering sessions',
    isSystem: true,
    permissions: ['read:self'],
  },
];

/**
 * Idempotent seed of the platform roles + their permission sets. Used by both the
 * dev seed script and the e2e test harness so register/login always find roles.
 */
export async function seedRolesAndPermissions(prisma: PrismaClient): Promise<void> {
  for (const roleSeed of SEED_ROLES) {
    const permissionIds: string[] = [];
    for (const name of roleSeed.permissions) {
      const permission = await prisma.permission.upsert({
        where: { name },
        update: {},
        create: { name, description: `Allows ${name}` },
      });
      permissionIds.push(permission.id);
    }

    const existing = await prisma.role.findUnique({
      where: { name: roleSeed.name },
      include: { permissions: { select: { id: true } } },
    });

    if (existing) {
      const existingIds = new Set(existing.permissions.map((p) => p.id));
      const newIds = new Set(permissionIds);

      const toDisconnect = existing.permissions
        .filter((p) => !newIds.has(p.id))
        .map((p) => ({ id: p.id }));
      const toConnect = permissionIds.filter((id) => !existingIds.has(id)).map((id) => ({ id }));

      if (toDisconnect.length > 0 || toConnect.length > 0) {
        await prisma.role.update({
          where: { name: roleSeed.name },
          data: {
            description: roleSeed.description,
            isSystem: roleSeed.isSystem,
            permissions: {
              disconnect: toDisconnect,
              connect: toConnect,
            },
          },
        });
      }
    } else {
      await prisma.role.create({
        data: {
          name: roleSeed.name,
          description: roleSeed.description,
          isSystem: roleSeed.isSystem,
          permissions: { connect: permissionIds.map((id) => ({ id })) },
        },
      });
    }
  }
}
