import { PrismaClient } from '@prisma/client';

export const SEED_ROLES: Array<{
  name: string;
  description: string;
  isSystem: boolean;
  permissions: string[];
}> = [
  {
    name: 'admin',
    description: 'Platform super administrator',
    isSystem: true,
    permissions: ['manage:all'],
  },
  {
    name: 'student',
    description: 'College student on the platform',
    isSystem: true,
    permissions: [
      'read:self',
      'read:sessions',
      'delete:sessions',
      'manage:student-profile',
      'manage:skills',
      'manage:career-goals',
      'manage:calendar',
      'manage:settings',
      'manage:notifications',
      'manage:readiness',
      'read:activity',
      'read:dashboard',
      'read:academics-departments',
      'read:academics-semesters',
      'read:academics-subjects',
      'read:academics-materials',
      'read:academics-timetable',
      'read:academics-exams',
      'read:academics-assignments',
      'create:academics-assignments',
      'read:academics-attendance',
      'read:academics-marks',
      'read:academics-gpa',
      'read:academics-cgpa',
      'read:academics-calendar',
      'read:placement-roadmap',
      'read:placement-company-prep',
      'read:placement-progress',
      'read:placement-readiness',
      'read:placement-daily-challenge',
      'create:placement-study-planner',
      'update:placement-tasks',
      'read:dsa-problems',
      'create:dsa-problems',
      'read:dsa-submissions',
      'create:dsa-submissions',
      'read:dsa-editorial',
      'read:dsa-hints',
      'create:dsa-hints',
      'read:dsa-playlists',
      'create:dsa-playlists',
      'update:dsa-playlists',
      'delete:dsa-playlists',
      'read:dsa-sheets',
      'read:dsa-progress',
      'read:dsa-analytics',
      'read:dsa-profile',
      'update:dsa-profile',
      'read:dsa-discussion',
      'create:dsa-discussion',
      'read:dsa-contests',
      'create:dsa-registrations',
      'read:dsa-leaderboard',
      'read:dsa-rating',
      'create:dsa-anti-cheat',
      'create:interviews',
      'read:interviews',
      'read:interview-reports',
      'read:career-coach-roadmap',
      'read:career-coach-recommendations',
      'read:career-coach-salary',
      'read:career-coach-skill-gap',
      'create:career-coach-chat',
      'read:career-coach-chat',
      'create:resumes',
      'read:resumes',
      'update:resumes',
      'delete:resumes',
      'read:resume-templates',
      'create:resume-ats',
      'read:resume-ats',
      'read:resume-versions',
      'create:resume-versions',
      'create:battle-queue',
      'delete:battle-queue',
      'create:battles',
      'read:battles',
      'create:battle-submissions',
      'read:battle-ratings',
      'read:battle-history',
    ],
  },
  {
    name: 'faculty',
    description: 'College faculty member',
    isSystem: true,
    permissions: [
      'read:self',
      'manage:faculty-subjects',
      'manage:faculty-materials',
      'manage:faculty-attendance',
      'manage:faculty-assignments',
      'manage:faculty-exams',
      'manage:faculty-marks',
      'manage:faculty-question-bank',
      'read:faculty-analytics',
      'read:dsa-contests',
      'create:dsa-contests',
      'update:dsa-contests',
      'delete:dsa-contests',
      'read:dsa-leaderboard',
      'read:dsa-rating',
    ],
  },
  {
    name: 'college_admin',
    description: 'College administrator',
    isSystem: true,
    permissions: [
      'read:self',
      'manage:departments',
      'manage:courses',
      'manage:faculty',
      'manage:students',
      'manage:academic-calendar',
      'read:academic-reports',
      'read:dsa-contests',
      'create:dsa-contests',
      'update:dsa-contests',
      'delete:dsa-contests',
      'read:dsa-leaderboard',
      'read:dsa-rating',
    ],
  },
  {
    name: 'recruiter',
    description: 'Company recruiter',
    isSystem: true,
    permissions: ['read:self'],
  },
  {
    name: 'tpo',
    description: 'Training & placement officer',
    isSystem: true,
    permissions: ['read:self'],
  },
  {
    name: 'parent',
    description: 'Parent of a student',
    isSystem: true,
    permissions: ['read:self'],
  },
  {
    name: 'mentor',
    description: 'Mentor offering sessions',
    isSystem: true,
    permissions: ['read:self'],
  },
];

/**
 * Idempotent seed of the platform roles + their permission sets. Used by both the
 * dev seed script and the e2e test harness so register/login always find roles.
 */
export async function seedRolesAndPermissions(prisma: PrismaClient): Promise<void> {
  for (const roleSeed of SEED_ROLES) {
    const permissionIds: string[] = [];
    for (const name of roleSeed.permissions) {
      const permission = await prisma.permission.upsert({
        where: { name },
        update: {},
        create: { name, description: `Allows ${name}` },
      });
      permissionIds.push(permission.id);
    }
    await prisma.role.upsert({
      where: { name: roleSeed.name },
      update: {
        description: roleSeed.description,
        isSystem: roleSeed.isSystem,
        permissions: { set: permissionIds.map((id) => ({ id })) },
      },
      create: {
        name: roleSeed.name,
        description: roleSeed.description,
        isSystem: roleSeed.isSystem,
        permissions: { connect: permissionIds.map((id) => ({ id })) },
      },
    });
  }
}
